name = "event-staff-assignment-app"
compatibility_date = "2025-09-25"

# Cloudflare Pages configuration for Next.js
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"